# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# docs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Install hurl (cross-platform)
description: Installs hurl binary file into your actions workflow

inputs:
  version:
    description: Hurl version
    required: true
    default: latest
  github-token:
    description: GitHub auth token. Since there's a default, this is typically not supplied by the user
    required: false
    default: ${{ github.token }}

outputs:
  hurl-bin:
    description: Path to the hurl binary file

runs:
  using: node20
  main: dist/index.js

branding:
  icon: compass
  color: blue
